Testing 1-2-3
natecox/pyshipstation pull request #19
Opened 2019-03-18 16:26 UTC by riveramj

![](https://media1.tenor.com/images/3f098f4963faa048846675941cef033e/tenor.gif)

Breaking up #18 into separate PRs.

This PR is unit tests for existing models.

2019-03-29 03:18 UTC, riveramj commented
Develop merged in. Ready for review.

2019-04-08 16:41 UTC, natecox commented
@riveramj Sorry for the delay on this, I've been dealing with a family illness issue that has eaten basically all of my time. I'll get back to this as soon as possible.

2019-04-11 03:16 UTC, riveramj commented
@natecox no worries. Good luck with everything.

2019-05-01 18:50 UTC, natecox requested changes
Looks good overall, requesting a formatting modification before merging.

2019-05-01 18:50 UTC, natecox commented on shipstation/api.py
> +        if not value or not isinstance(value, (int, float, Decimal)):
I know this seems nitpicky, but I strongly prefer that all conditional blocks end with whitespace to show relation (or lack thereof).

```python
if some_condition:
    do_something()

if some_other condition:
    do_something_else()
else:
    fallback()

if a_third_condition:
    do_something()
elif alternative_to_third_condition:
    do_something_else()
else:
    fallback()

```

2022-01-24 00:28 UTC, natecox commented
I'm moderately certain this PR is invalidated by the previous ones I just merged in. Feel free to re-open and correct me if I'm wrong.

2022-01-24 00:28 UTC, closed without merging